### ISSUE TITLE
err_exit() undefined

### ISSUE THREAD

**Issue by StewMH** [htcondor/htcondor-ce#245]
Hi,

err_exit is used in verify_ce_config.py but not defined anywhere else. I ran into this when my CE setup was ill-defined, but it made it slightly harder to debug:
```
Traceback (most recent call last):
condor_ce_startup[254141]: File "/usr/share/condor-ce/verify_ce_config.py", line 90, in <module>
condor_ce_startup[254141]: err_exit("HTCondor batch system is improperly configured for use with HTCondor CE. " \
condor_ce_startup[254141]: NameError: name 'err_exit' is not defined
condor-ce.service: control process exited, code=exited status=6
```

Cheers,

Stewart

**Comment by bbockelm** [comment]
Thanks for the bug report @StewMH!  I assigned this bug and we'll try to get to this in the next release.

**Comment by brianhlin** [comment]
I had this fixed in a WIP branch but forgot to get it into 4.0.0. Sorry about that! I'll cut a quick 4.0.1

**Comment by StewMH** [comment]
Thanks!
