### ISSUE TITLE
Inconsistent BDII documentation/examples

### ISSUE THREAD

**Issue by maxfischer2781** [htcondor/htcondor-ce#320]
The BDII documentation/examples are inconsistent with what the code does.

For example,
* [Docs](https://htcondor-ce.readthedocs.io/en/stable/installation/htcondor-ce/#enabling-bdii-integration) refer to ``/etc/condor-ce/config.d/99-ce-bdii.conf`` but the file is ``/etc/condor/config.d/99-ce-bdii.conf``
* [Example uses HTCONDORCE_SiteName](https://github.com/htcondor/htcondor-ce/blob/2a5f9f19535c5352d6008c2afca54dc8f52d6c04/contrib/bdii/99-ce-bdii.conf#L9) but the code uses ``GLUE2DomainID``
* The HTCONDORCE_CORES parameter is not used in the code

PS: I don't mind providing a PR if you can clarify whether code or docs are meant to be authorative.

**Comment by brianhlin** [comment]
Hi @maxfischer2781 could you run `rpm -q htcondor-ce` to tell me what version/source of HTCondor-CE you're running?

**Comment by brianhlin** [comment]
Hi @maxfischer2781, turns out I had time to look into this so I've fixed the docs and updated the configuration and code so that they're consistent. This should make it into the next release of HTCondor-CE 3 and 4. Thanks for the report!
