### ISSUE TITLE
Inconsistent APEL permissions/user

### ISSUE THREAD

**Issue by maxfischer2781** [htcondor/htcondor-ce#323]
It seems the ``htcondor-ce-apel`` is written with a regular cronjob (as ``root``) in mind, not a Schedd_Cron job (as ``condor``). The standard permissions of ``/var/lib/condor-ce/apel/`` and ``/var/log/apel/`` prevent the ``condor`` user from writing to them, causing the Schedd_Cron job to fail.

I'm not sure whether permissions of the folders should be changed, or the job should be run as root. Only the ``/var/lib/condor-ce/apel/`` folder is created by ``htcondor-ce-apel``.

**Comment by brianhlin** [comment]
Hi @maxfischer2781, thanks for the report! I'm curious, if you change the `logfile` in `/etc/apel/logging.cfg` and `/etc/apel/client.cfg` to a path that the `condor` user can write to, does that solve the issue with `/var/log/apel/`?

**Comment by maxfischer2781** [comment]
Yes, changing the logfile to a writeable location fixes the problem. The paths in ``/etc/apel/client.cfg`` (default ``logfile = /var/log/apel/client.log``), ``/etc/apel/parser.cfg``(default ``logfile = /var/log/apelparser.log``), and ``/etc/apel/sender.cfg`` (default ``logfile: /var/log/apel/ssmsend.log``) need changing.

**Comment by maxfischer2781** [comment]
Just a heads-up that we've missed some other paths (due to tinkering with permissions) that APEL will attempts to write to by default as root. These are all below ``/var/spool/apel/``, ``/var/log/apel/``, plus ``/var/log/apelparser.log``. Subdirectories are created for the current user, e.g. ``/var/spool/apel/outgoing/`` as ``drwxr-xr-x``.

**Comment by brianhlin** [comment]
Hi @maxfischer2781, I think we're going to have to abandon the idea of running the APEL tools as a non-root user via `SCHEDD_CRON`. There are just too many paths that we're having users change in their configurations -- the next version(s) of HTCondor-CE will have systemd units and timers and cron jobs for the APEL integration

**Comment by maxfischer2781** [comment]
Thanks a lot, that seems viable. I'll work around the issue manually for now.

**Comment by brianhlin** [comment]
Resolved by #330 and #334
