### ISSUE TITLE
CEViewLog created with root ownership

### ISSUE THREAD

**Issue by matyasselmeci** [htcondor/htcondor-ce#341]
condor_ce_view apparently creates `/var/log/condor-ce/CEViewLog` owned by root:root the first time it runs. This is fine because it has already opened the log, but if it ever gets restarted, it will not be able to reopen it for writing due to lack of privileges and will exit. Manually chowning CEViewLog to condor:condor fixes the issue.

**Comment by ColeBollig** [comment]
This has been translated into HTCONDOR-1647
