### ISSUE TITLE
Enable Negotiator for job usage statistics

### ISSUE THREAD

**Issue by brianhlin** [htcondor/htcondor-ce#345]
The HTCondor Negotiator daemon provides some historical statistics of job usage so we'd like to enable it. However, pilot startd's are allowed to advertise back to the site CE collector so we need to disable negotiation so that incoming pilots don't match to those startd's. According to the HTCondor developers, we can set the following to disable negotation:

```
NEGOTIATOR_SUBMITTER_CONSTRAINT = false 
```

**Comment by ColeBollig** [comment]
This has been translated into HTCONDOR-1646
