### ISSUE TITLE
Various minor CEView UI issues

### ISSUE THREAD

**Issue by matyasselmeci** [htcondor/htcondor-ce#346]
- [ ] Main page: the "Pilots" and "Info" tables take a couple of seconds to load and look blank until then. Maybe add some "Loading..." text so the user doesn't think something's broken.
- [ ] [VOs page](https://collector1.opensciencegrid.org/vos) could also use the "Loading..." text, and is also blank if you don't have any VOs; maybe some text saying "you don't have any VOs" so the user doesn't think something's broken.

**Comment by ColeBollig** [comment]
Change close type
