### ISSUE TITLE
Support for Multiple COLLECTOR HOST

### ISSUE THREAD

**Issue by aleita** [htcondor/htcondor-ce#364]
It seems the information provider [htcondor-ce-provider] does not support the case where 
COLLECTOR_HOST has multiple hosts defined with a comma separated list of hosts

```
    # Get hostname of the batch system central manager
    central_manager = htcondor.param.get('COLLECTOR_HOST').split(' ')[0] 
```

```
>>> import htcondor 
>>> import classad
>>>
>>> htcondor.param.get('COLLECTOR_HOST').split(' ')[0] 
'htc-ctl-01,'
>>> 
```

**Comment by brianhlin** [comment]
Hi @aleita, are these HA collectors (e.g. just backups containing the same ads) or do they all contain different ads?

**Comment by aleita** [comment]
just backup. Both collector contains the same ads

[root@ce-01 ~]# condor_config_val -v COLLECTOR_HOST
COLLECTOR_HOST = htc-ctl-01, htc-ctl-02
 # at: <Default>
 # raw: COLLECTOR_HOST = $(CONDOR_HOST)

[root@ce-01 ~]#

**Comment by aleita** [comment]
this is the output of the provider

[root@ce-05 ~]# /var/lib/bdii/gip/provider/htcondor-ce-provider
dn: GLUE2ResourceID=htc-ctl-01,_x86_64_linux_CentOS_7_24_80372,GLUE2ServiceID=htc-ctl-01,,GLUE2GroupID=resource,o=glue
....

there is an extra comma in the Distinguished Name

**Comment by brianhlin** [comment]
Thanks for the info @aleita. Would you expect the provider to publish information for both `htc-ctl-01` and `htc-ctl-02` or is just one of them sufficient?

**Comment by kreczko** [comment]
In our case just one is sufficient (HA pair). Our htcondor-ce-provider patch is
```python
 central_manager = htcondor.param.get('COLLECTOR_HOST').strip().split(',')[0]
```
to get rid of spaces as well (our managers are defined as `htc00.dice.priv, htc01.dice.priv`).
But of course, such a patch ignores the HA setup.

**Comment by aleita** [comment]
sorry for the late answer.

just one is sufficient

**Comment by brianhlin** [comment]
> In our case just one is sufficient (HA pair). Our htcondor-ce-provider patch is
> 
> ```python
>  central_manager = htcondor.param.get('COLLECTOR_HOST').strip().split(',')[0]
> ```
> 
> to get rid of spaces as well (our managers are defined as `htc00.dice.priv, htc01.dice.priv`).
> But of course, such a patch ignores the HA setup.

@kreczko do you know if this actually matters to BDII? The provider currently only grabs the first collector so I was leaning towards a similar solution.

**Comment by kreczko** [comment]
@brianhlin Since the central_manager is only used for the BDII output and not for actual htcondor queries, it does not matter.

**Comment by andiri** [comment]
Hi, 

we have a setup with two collector hosts, not in HA but independent condor pools in one site. As each of collector publishes different ads (number of machines, cpu spec, memory, etc.), htcondor-ce-provider should publish both, however as reported above, currently it publishes site information from one collector. 

It would be helpful for the case like us that the provider can accumulate all of ads, at least e.g. total logical cpus and some other ads that can be fine for accumulation, from available collectors and add them to the database. For sure, in such a case of HA collectors, the accumulation should be avoided. Or it would be great as well if the provider can treat independently each of collectors not in HA. 

Thank you.

Best regards,
Sang-Un

**Comment by andiri** [comment]
Hi Brian,

I am using 3.4.0 for htcondor-ce. If the fix will be availble only for htcondor-ce 4, then I am willing to upgrade it. 

Thank you. 

Best regards,
Sang-Un

**Comment by aleita** [comment]
Hi Brian,

[root@ce-02 ~]# condor_ce_q --version
$CondorVersion: 8.8.10 Aug 05 2020 BuildID: 513586 PackageID: 8.8.10-1 $
$CondorPlatform: x86_64_CentOS7 $

[root@ce-02 ~]# rpm -qa | grep condor-ce
htcondor-ce-condor-3.4.3-1.el7.noarch
htcondor-ce-view-3.4.3-1.el7.noarch
htcondor-ce-3.4.3-1.el7.noarch
htcondor-ce-bdii-3.4.3-1.el7.noarch
htcondor-ce-client-3.4.3-1.el7.noarch
htcondor-ce-apel-3.4.3-1.el7.noarch
[root@ce-02 ~]#

Ale

**Comment by brianhlin** [comment]
Hi @aleita and @andiri: sorry for the radio silence on this. We had to make changes to add support for Python 3 and EL8 so this got put on the backburner, especially since both tasks would touch a lot of the same code. For the VOs that you support, do you do you know of the long-term plans for BDII? As I understand it, many of the WLCG VOs are moving over to CRIC

**Comment by ColeBollig** [comment]
The Center for High Throughput Computing (CHTC) has decided to disable the issues functionality for this github repository. While this issue is still marked as open, we will be considering it as resolved due to it being stale. If this issue is not resolved please contact us via the mailing list: htcondor-users@cs.wisc.edu
