### ISSUE TITLE
CE enforces $HOME on resources

### ISSUE THREAD

**Issue by maxfischer2781** [htcondor/htcondor-ce#374]
We're having problems for some jobs that have different `$HOME` on the CE as on the compute resources.  It appears that the CE forces jobs to use ``$HOME`` regardless of the compute resource:
https://github.com/htcondor/htcondor-ce/blob/633ed40be67ba818a77f305add96dcea8add78ab/src/condor_ce_router_defaults#L27
This is problematic in our case, since some compute resources have different home folders than the CE for historical reasons.

Is there a reason why the CE tries to enforce `$HOME`, instead of having the compute resources set it themselves?

**Comment by brianhlin** [comment]
Hrm, this was added quite early on in CE development and I can't recall the reasoning :(. I'm hesitant to remove this in case folks are unknowingly dependent on this behavior. Let me see if I can find a clean way of overriding this via configuration.

**Comment by brianhlin** [comment]
Unfortunately it's not easy to override this via config but #377 adds a config option so that you can disable this behavior
