### ISSUE TITLE
htcondor-ce-bdii  rpms dependencies

### ISSUE THREAD

**Issue by evamvak-source** [htcondor/htcondor-ce#379]
Dear  Brian

it is possible to remove the htcondor-ce.noarch  rpm from dependencies of htcondor-ce-bdii
in order to facilte the installation  of  htcondor-ce-bdii in a machibe with out htcondor-CE

e.g
repoquery --requires --resolv htcondor-ce-bdii
htcondor-ce-0:4.4.1-1.el7.noarch
coreutils-0:8.22-23.el7.x86_64
bdii-0:5.2.25-2.el7.noarch

thank you in advance
e.v.

**Comment by brianhlin** [comment]
Hi @evamvak-source , looking at the provider, I think we should be able to remove that requirement in the next release of HTCondor-CE 4
