### ISSUE TITLE
htcondor-ce-provider and published resources 

### ISSUE THREAD

**Issue by evamvak-source** [htcondor/htcondor-ce#380]
Dear Brian 
on htcondor-ce-provider we have , 

- GLUE2ExecutionEnvironmentLogicalCPUs which correspond to "the number of processors seen by the operating system on one Worker"
- GLUE2ExecutionEnvironmentMainMemorySize: {memory} which correspond to "the  available physical memory  seen by the operating system on one Worker"

on CC  we have to make modification on htcondor-ce-provider  and 

GLUE2ExecutionEnvironmentLogicalCPUs  corresponds to the total number of detected logical CPUs
GLUE2ExecutionEnvironmentMainMemorySize corresponds to the available physical memory per logical CPUs. 

due to ticket GGUS 
https://ggus.eu/index.php?mode=ticket_info&ticket_id=142898
and 
https://ggus.eu/index.php?mode=ticket_info&ticket_id=146122

Finally which is the general usage of this two attributes? 
Should be our change become general on htcondor-ce-bdii release ?
FYI
e.v.
ps
see at 10p-11p 
https://indico.cern.ch/event/817927/contributions/3570566/attachments/1915553/3167163/HTCondor-CE-at-CC.pdf

**Comment by brianhlin** [comment]
As discussed on our call, I believe that this should be fixed when we fix #376
