### ISSUE TITLE
BDII and APEL integration for non-CONDOR batch grid types

### ISSUE THREAD

**Issue by fnevgeny** [htcondor/htcondor-ce#393]
Hello,

Can you please clarify whether htcondor-ce can be integrated with other batch systems, e.g. OpenPBS? The docs in general say other batch systems are supported, but the section about BDII talks only about HTCondor. Same about APEL.

Thanks,
Evgeny

**Comment by brianhlin** [comment]
Hi Evgeny, we do not currently support APEL/BDII with non-HTCondor batch systems. We certainly take and appreciate any contributions if you feel particularly moved to implement it on your own! I'll update the docs accordingly.

**Comment by fnevgeny** [comment]
Hi Brian,

Thanks for the prompt reply. Can you please provide pointers to begin with - and at least a very rough estimate of work it might take to implement?

**Comment by brianhlin** [comment]
Hi Evgeny,

I think APEL would be the easier of the two: you'd have to just generate the batch record and slightly modify the blah record so that the apelparser can combine the two on the linked job IDs. BDII is a lot trickier since the CE and batch bits are entangled in the same provider, and BDII requirements are always tricky to nail down. I'd wager that would take work on the order of weeks.

- Brian

**Comment by fnevgeny** [comment]
> BDII is a lot trickier since the CE and batch bits are entangled in the same provider

Do you mean it's tricky to fetch the relevant info from the batch manager using only the HTCondor-CE functionality? But what if I have direct access to both (or rather intend to configure both pbs and htcondor-ce from the same system, e.g., yaim or puppet)?

Thanks for updating the docs. I would like to understand, what would be a real life scenario for installing htcondor-ce with a non-htcondor batch system, given the BDII and APEL integrations are not (yet) there?

**Comment by brianhlin** [comment]
> Do you mean it's tricky to fetch the relevant info from the batch manager using only the HTCondor-CE functionality? But what if I have direct access to both (or rather intend to configure both pbs and htcondor-ce from the same system, e.g., yaim or puppet)?

The [current provider](https://github.com/htcondor/htcondor-ce/blob/master/contrib/bdii/htcondor-ce-provider#L315-L316) depends on a local HTCondor pool's central manager to generate the batch system and CE LDIFs. If you have direct access to both PBS and your HTCondor-CEs, then you should be able to construct the LDIFs by hand.

> Thanks for updating the docs. I would like to understand, what would be a real life scenario for installing htcondor-ce with a non-htcondor batch system, given the BDII and APEL integrations are not (yet) there?

If the grid you are contributing to doesn't use APEL or BDII for its accounting or information services then you can forego both packages! For example, the OSG uses the [HTCondor-CE Central Collector](https://htcondor-ce.readthedocs.io/en/latest/installation/central-collector/) for information services and their own accounting system, for which they maintain the non-HTCondor batch system support.

**Comment by fnevgeny** [comment]
Thank you for your clarifications, Brian!

I'm closing the ticket.
