### ISSUE TITLE
Jobs missing in APEL records versus condor_history

### ISSUE THREAD

**Issue by maxfischer2781** [htcondor/htcondor-ce#419]
We occasionally see a significant number of jobs missing from APEL – about %5 to 10%. The jobs are in `condor_history` but do not get written out to the APEL records:

```bash
$ condor_history -match 1 3100000.0 -file /backup/htcondor-ce-1-kit/condor_history_20210131
 ID     OWNER          SUBMITTED   RUN_TIME     ST COMPLETED   CMD
3100000.0   plhcb49         1/31 06:35   0+02:03:37 C   1/31 08:39 DIRAC__sCOtw_pilotwrapper.py
$ grep ^309999 /var/lib/condor-ce/apel/batch-202101*-htcondor-ce-1-kit  # jobs before
/var/lib/condor-ce/apel/batch-20210131-htcondor-ce-1-kit:3099992.0_htcondor-ce-1-kit.gridka.de|alicesgm|47738|42537|595|1612071724|1612119462|2046508|6599748|1|1.069035087719298|
/var/lib/condor-ce/apel/batch-20210131-htcondor-ce-1-kit:3099996.0_htcondor-ce-1-kit.gridka.de|atlasprd|23975|177846|5667|1612076854|1612100829|8745192|42251352|8|0.9114035087719299|
/var/lib/condor-ce/apel/batch-20210131-htcondor-ce-1-kit:3099991.0_htcondor-ce-1-kit.gridka.de|atlasprd|22693|169983|9477|1612076855|1612099548|9823420|43896844|8|0.9151754385964912|
/var/lib/condor-ce/apel/batch-20210131-htcondor-ce-1-kit:3099997.0_htcondor-ce-1-kit.gridka.de|atlasprd|20630|154714|10286|1612077309|1612097939|9061048|43332508|8|0.9151754385964912|
/var/lib/condor-ce/apel/batch-20210131-htcondor-ce-1-kit:3099993.0_htcondor-ce-1-kit.gridka.de|atlasprd|19886|146123|5000|1612076854|1612096740|8949180|42814016|8|0.9114035087719299|
/var/lib/condor-ce/apel/batch-20210131-htcondor-ce-1-kit:3099990.0_htcondor-ce-1-kit.gridka.de|alicesgm|19538|7415|364|1612071725|1612091263|2143792|9827460|1|0.9114035087719299|
/var/lib/condor-ce/apel/batch-20210131-htcondor-ce-1-kit:3099999.0_htcondor-ce-1-kit.gridka.de|plhcb49|10591|10278|71|1612071368|1612081959|1070996|3675820|1|0.9151754385964912|
$ grep ^310000 /var/lib/condor-ce/apel/batch-2021*-htcondor-ce-1-kit  # jobs including and after
/var/lib/condor-ce/apel/batch-20210131-htcondor-ce-1-kit:3100008.0_htcondor-ce-1-kit.gridka.de|plhcb49|17625|16803|583|1612071366|1612088991|2849484|7172200|1|1.205701754385965|
/var/lib/condor-ce/apel/batch-20210131-htcondor-ce-1-kit:3100001.0_htcondor-ce-1-kit.gridka.de|plhcb49|10862|10736|54|1612071368|1612082230|1103812|3734920|1|0.9151754385964912|
/var/lib/condor-ce/apel/batch-20210131-htcondor-ce-1-kit:3100004.0_htcondor-ce-1-kit.gridka.de|plhcb49|10778|10640|51|1612071368|1612082146|1085364|3693448|1|0.9151754385964912|
/var/lib/condor-ce/apel/batch-20210131-htcondor-ce-1-kit:3100002.0_htcondor-ce-1-kit.gridka.de|plhcb49|9821|9656|81|1612071368|1612081189|1105348|3707284|1|0.9151754385964912|
```

We also see that entire days are missing records:
```bash
$ ls batch-202102*
batch-20210201-htcondor-ce-1-kit  batch-20210204-htcondor-ce-1-kit  batch-20210207-htcondor-ce-1-kit  batch-20210210-htcondor-ce-1-kit
batch-20210203-htcondor-ce-1-kit  batch-20210205-htcondor-ce-1-kit  batch-20210208-htcondor-ce-1-kit
```
Notably, these two are related but seem not identical – jobs appear to be missing even when records exist for each day. In short, the way that records are created is not robust.

**Comment by maxfischer2781** [comment]
The missing records seem to be caused by APEL taking very long for database operation when the job count is high.
```
Feb 08 04:18:31 htcondor-ce-1-kit condor_ce_apel.sh[2550518]: 2021-02-08 04:18:31,559 - client - INFO - =====================
Feb 08 04:18:31 htcondor-ce-1-kit condor_ce_apel.sh[2550518]: 2021-02-08 04:18:31,559 - client - INFO - Starting joiner.
Feb 08 04:18:31 htcondor-ce-1-kit condor_ce_apel.sh[2550518]: 2021-02-08 04:18:31,559 - apel.db.backends.mysql - INFO - Creating JobRecords
Feb 09 17:20:22 htcondor-ce-1-kit condor_ce_apel.sh[2550518]: 2021-02-09 17:20:22,873 - apel.db.backends.mysql - INFO - Done.
Feb 09 17:20:22 htcondor-ce-1-kit condor_ce_apel.sh[2550518]: 2021-02-09 17:20:22,904 - client - INFO - Joining complete.
Feb 09 17:20:22 htcondor-ce-1-kit condor_ce_apel.sh[2550518]: 2021-02-09 17:20:22,904 - client - INFO - =====================
```
This can take more than 24h. Since the record creating scripts and APEL DB operations run on the same systemd service/timer, the record scripts are not run daily in this case.

**Comment by brianhlin** [comment]
Hi @maxfischer2781 thanks for the report! Ideally, HTCondor-CE would only be responsible for record generation and record upload with an `ssmsend` service provided by APEL folks. If that doesn't work out, we can separate out generation/upload into separate serivces+timers but I'm hesitant about making that change for stable (i.e., HTCondor-CE 3). What version of HTCondor-CE are you running again?

**Comment by maxfischer2781** [comment]
We are currently on stable/v3. I'm fine with the change going to either version – as long as we know the "official" fix our configuration management can replicate that until we are on a more recent version.

As a hotfix, we currently run ``apel_batch.sh``/``apel_blah.sh`` with cron in addition to their run via ``condor_ce_apel`` – that should work outside of the unlikely race condition that cron rewrites the records just as APEL reads them. Looking at the scripts and APEL, separating ``apel_batch.sh``/``apel_blah.sh`` from ``apelparser``/``apelclient``/``ssmsend`` seems like the proper setup indeed.

**Comment by brianhlin** [comment]
Yeah, I think separating them out makes the most sense. Do you know if the APEL folks package a service for `apelparser`/`apelclient`/`ssmsend`? It seems wrong for the CE to package such a service.

Also, should we consider generating records more frequently to reduce the possibility/effect of the CE record generation failing?

**Comment by maxfischer2781** [comment]
We currently generate records twice a day as a fail-safe hotfix. So, that works more robustly already.

However, IMO the proper approach is to store the "last recorded" timestamp after writing a record successfully. The next time a record is created, it would start picking jobs after the "last recorded" timestamp. (That would also work well for increasing/decreasing the frequency.)  
As far as I can tell, APEL would work fine with that. It just reads any new records when it runs, with no concept of hourly/daily/... record creation.

**Comment by brianhlin** [comment]
Hi @maxfischer2781 that sounds like a solid solution but I think using the same model as OSG's Gratia probe would probably be the most robust:

1. Set [`PER_JOB_HISTORY_DIR`](https://htcondor.readthedocs.io/en/latest/admin-manual/configuration-macros.html#PER_JOB_HISTORY_DIR) in the local HTCondor config
2. Generate an APEL blah and batch record off of a history file
3. Clean-up the history file if the records are created, otherwise quarantine them so admins can review them

This way, we'd only miss accounting for malformed job ads instead of potentially having missed jobs that completed earlier than the last timestamp. If that sounds good, I'll create a ticket for the HTCondor team.

**Comment by maxfischer2781** [comment]
That sounds *very* good.

**Comment by brianhlin** [comment]
Ticket created in our Jira: https://opensciencegrid.atlassian.net/browse/HTCONDOR-293. I'll leave this issue open since we don't have public commenting in our Jira instance.

**Comment by markcoatsworth** [comment]
Hi @maxfischer2781 I've been working with Brian on this new script. Important question: what are you expecting for output? Right now our scripts produce two files every day (ie. `batch-20210311-ce_hostname` and `blah-20210311-ce_hostname`). Brian suggested that we should collect data every hour instead of daily. So would you now expect to see files that have the hour timestamp in the filename, ie. `batch-20210311-1300-ce_hostname` and `blah-20210311-1400-ce_hostname`?

**Comment by maxfischer2781** [comment]
To add some background: APEL basically just does a glob akin to ``${LOGDIR}/blah*`` and ``${LOGDIR}/batch*``, then filters out all the filenames already parsed previously. So you have lots of freedom in the format.

Any format that includes both date and time seems fine to me. 👍 to ``batch-20210311-1300-ce_hostname`` etc. from my side.

**Comment by maxfischer2781** [comment]
Just a heads up that we are currently testing whether the v5 changes are sufficient to fix the problem in production. Will take a bit since there is low throughput on the test instance and we have to take care of all the bits that changed.

**Comment by maxfischer2781** [comment]
Okay, so the change is working in principle. There's one issue that I'm not sure how to solve best:

The [default ``PER_JOB_HISTORY_DIR`` of ``/var/lib/condor/history``](https://github.com/htcondor/htcondor-ce/blob/e35688a240daac636f927ad56da41c6e69b64155/contrib/apelscripts/50-condor-apel.conf#L12) is owned by ``root:root`` on both my two test systems. It must be ``condor:condor`` for the Schedd to write to it – right now the Schedd silently discards the records. Manually fixing the ownership makes the entire APEL pipeline work (yay!).
Now, I have no idea how the folder actually gets created – it doesn't seem to be created as part of the RPM – so no idea how to fix it properly. Where should the ownership be set, ideally?

**Comment by brianhlin** [comment]
Hi @maxfischer2781 thanks for the feedback and good catch. I think the dir is being created with `root:root` ownership because of this line https://github.com/htcondor/htcondor-ce/blob/V5-branch/contrib/apelscripts/condor_batch_blah.sh#L30 and the fact that it's being run as a rootly systemd service. It looks like we should be able to drop privs for that entire script so I'll take that to the HTCondor team

**Comment by maxfischer2781** [comment]
In that case, you might also want to reconsider splitting record-generation from record-parsing/-sending, by running ``condor_batch_blah.sh`` via Schedd Cron and APEL itself via cron/systemd/…. It looks like [APEL is packaged to expect being run as `root`](https://github.com/apel/apel/blob/f46ba48eec0ebfcf1068174e0b5c7a73e3e35db8/apel.spec#L143).

Let me know if I can help with anything, e.g. running APEL as another user.

**Comment by brianhlin** [comment]
Actually...I don't think we can run the record generation as a `SCHEDD_CRON` since the destination dir has `root:root` ownership and HTCondor/HTCondor-CE doesn't control that dir, IIRC. Is that right @maxfischer2781 ?

**Comment by maxfischer2781** [comment]
Had to check that thoroughly...

The directory is controlled by the CE: The default directory ``APEL_OUTPUT_DIR = /var/lib/condor-ce/apel/`` is [created by the RPM](https://github.com/htcondor/htcondor-ce/blob/26704cb0a5a8425e05672a094435e22e6e2ad4e2/rpm/htcondor-ce.spec#L241). It's currently ``drwxr-xr-x root root`` but I don't see a problem changing it to the condor user; APEL just needs to read from it.

FWIW, I don't see anything wrong with having the RPM create the default history dir as ``condor:condor`` and calling it a day. (The ``SCHEDD_CRON`` would be nice, but then again accounting isn't about that...)

**Comment by maxfischer2781** [comment]
Using the current v5 code in production, the HTCondor-CE APEL plugin a) works out of the box and b) doesn't miss any job records. That's about it for the HTCondor-CE side of things, as far as I can tell. \*closing\*

--------------

In case someone else digs up this issue because APEL itself cannot process the records fast enough: We have *not* been able to pinpoint the performance issue in APEL / APEL's HTCondor backend. It looks like the issue is related to having a huge history in the APEL DB, and might be worsened by having orphan CE/LRMS job records. The APEL developers are looking into optimising the database queries which should fix/remedy this in the long run.

We (WLCG Tier1 FZK) still observe a gradual slow-down over time, but it does not seem directly correlated to the age of the machine/installation/APEL. In any case, iff the issue occurs for someone else it appears that dropping old records from the APEL database should be sufficient.
