### ISSUE TITLE
CondorCE unit should not start, when execute and spool directories are missing

### ISSUE THREAD

**Issue by thdesy** [htcondor/htcondor-ce#430]
Dear Developers,

since one of our CondorCE behaved somewhat odd, I tried to nuke all its spool/history/job_queue for a clean slate (same for the Condor spool dir).

To do so, I stopped the `condor-ce.service` unit, moved the CE's spool content under `/var/lib/condor-ce/*` and started the `condor-ce.service` unit again

Since on a  quick glance, the unit started and appeared active/running, I did not noticed due to neglect, that the CE had actually failed to start up properly - as I had removed its `spool` & `execute`

- Suggested behaviour:
the service unit should fail when the spool/execute directories are not writable

Optionally, the unit file could require the existence of the paths
  ConditionPathExists=/var/lib/condor-ce/spool
  ConditionPathExists=/var/lib/condor-ce/execute
as an initial condition.
Probably systemd's `StateDirectory` together with `User` could be used here to ensure the parent directory- but I would have to test it.

Since it was clearly a user error, I guess the severity is pretty low...

Cheers,
  Thomas

[1]

> systemctl status condor-ce
● condor-ce.service - HTCondor CE
   Loaded: loaded (/etc/systemd/system/condor-ce.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-03-05 12:45:23 CET; 1h 39min ago
  Process: 4148214 ExecStop=/usr/bin/condor_ce_off (code=exited, status=1/FAILURE)
  Process: 4150612 ExecStart=/usr/share/condor-ce/condor_ce_startup (code=exited, status=0/SUCCESS)
 Main PID: 4150663 (condor_master)
    Tasks: 6
   Memory: 20.4M
   CGroup: /system.slice/condor-ce.service
           ├─4150663 condor_master
           ├─4150729 condor_procd -A /var/lock/condor-ce/procd_pipe -L /var/log/condor-ce/ProcLog -R 1000000 -S 60 -C 994
           ├─4150730 condor_shared_port
           ├─4150739 condor_collector
           ├─4150743 condor_job_router
           └─4150749 condor_gangliad

Mar 05 12:45:21 grid-htcondorce0.desy.de systemd[1]: Starting HTCondor CE...
Mar 05 12:45:21 grid-htcondorce0.desy.de condor_ce_startup[4150612]: stat: cannot stat ‘/var/lib/condor-ce/spool’: No such file or directory
Mar 05 12:45:21 grid-htcondorce0.desy.de condor_ce_startup[4150612]: stat: cannot stat ‘/var/lib/condor-ce/execute’: No such file or directory
Mar 05 12:45:22 grid-htcondorce0.desy.de htcondor[4150708]: Not changing TCP_LISTEN_QUEUE (/proc/sys/net/core/somaxconn): new value (1024) <= old value (1024).
Mar 05 12:45:23 grid-htcondorce0.desy.de systemd[1]: Started HTCondor CE.

**Comment by brianhlin** [comment]
Hi @thdesy, thanks for the report! We do try to verify `condor:condor` ownership (https://github.com/htcondor/htcondor-ce/blob/V5-branch/src/condor_ce_startup#L14-L18) of those dirs among others but it looks like we don't check for existence!

**Comment by timtheisen** [comment]
FYI, HTCondor version 8.9.12 and later will create the required directories on startup.

**Comment by brianhlin** [comment]
Hi @thdesy in light of Tim's comment, I'm going to close this issue since this will be automatically addressed by HTCondor
