### ISSUE TITLE
APEL - Make apelclient and ssmsend optional in condor_ce_apel.sh

### ISSUE THREAD

**Issue by drebatto** [htcondor/htcondor-ce#431]
Hi! 
The script `/usr/share/condor-ce/condor_ce_apel.sh` would need a little modification. The last two steps, namely `apelclient` and `ssmsend`, should be made optional because in many deployments APEL uses a central publisher, so the CEs don't send usage records to the central accounting system directly.
I'd propose to use an 'APEL_USE_PUBLISHER' configuration knob somewhere in the APEL-related configuration files to skip the last two steps.
I'll try to make a patch and create a pull request, but there are many ways to implement that so I hope to get the "CE-style" right.

**Comment by brianhlin** [comment]
Fixed by #433
