### ISSUE TITLE
Simplify APEL accounting: Average and per-machine performance

### ISSUE THREAD

**Issue by maxfischer2781** [htcondor/htcondor-ce#542]
Simplify APEL accounting: Average and per-machine performance

Currently APEL resource usage reporting for HTCondor-CE work via an average performance absolute score on the CE and an individual performance scaling factor on each worker node. There are some issues with this approach:
- In a homogeneous cluster, one still needs to configure a "dummy" scaling factor of 1 for each worker node.
- In a heterogeneous cluster, one must publish the average to each worker node to compute its scaling factor.

The former is quite a hassle that makes a minimal setup needlessly complicated. The latter is especially bad in large and/or opportunistic clusters since the average can change frequently; accurately maintaining both average score and per-machine factor at scale is next to impossible. FWIW, it looks like one can in principle disable scaling for the entire cluster but this seems to be undocumented.

I propose to make the homogeneous case simpler to configure and the heterogeneous case simpler to get right but would like feedback before drafting a PR.

-----------

From the APEL side, we have
* an average performance score for the CE itself of a specific type (e.g. `HEPSPEC`) and value (e.g. `13.45`) in `client.cfg`:
   ```
   manual_spec1 = htcondor-ce-1-kit.gridka.de:9619/htcondor-ce-1-kit.gridka.de-condor,HEPSPEC,13.45
   ```
* an [*optional* scaling factor for each job defaulting to 1.0](https://github.com/apel/apel/blob/ef23b80716da51d44a18a82ebf594faaa2e50cf0/apel/parsers/htcondor.py#L47-L49) in each job record.

APEL takes care of matching the average performance to the scale factor (actually, the job) based on the definition time of the `manual_specX` and the end-time of the job.

For the homogeneous case what APEL provides is already sufficient: When creating job records, **if no scaling is available either skip the scaling factor or set it to 1.**
* Should there be an option to force scaling/performance to be set, e.g. to detect configuration errors?

For the heterogeneous case, it would be more robust to **compute the scale factor on the CE**: The StartD/Job would supply an absolute performance and when creating job records **the script would compute the scale factor from the StartD/Job performance and the APEL performance.**
* Should there be a way to provide different performance types (`HEPSPEC`, `SI2K`, ...)?

**Comment by thdesy** [comment]
with the new HEP benchmark(s) probably an option to give multiple benchmarks could become handy (for the price of adding another dimension...)

**Comment by brianhlin** [comment]
Thanks for creating the issue @maxfischer2781! A few comments/questions:

> an average performance score for the CE itself of a specific type (e.g. HEPSPEC) and value (e.g. 13.45) in client.cfg:

Is this `client.cfg` part of the APEL configuration? Or does this have to live in the HTCondor-CE configuration?

> Should there be an option to force scaling/performance to be set, e.g. to detect configuration errors?

It sounds like if we want to support easy configuration of a homogenous cluster (i.e., assuming a scaling factor of 1.0) then we can't do any config validation.

> Should there be a way to provide different performance types (HEPSPEC, SI2K, ...)?

Yes, we're very interested in supporting the new HEPSCORE benchmarks sometime this summer so this is definitely something we'll need!

> Since HTCondor-CE relies heavily on Python3 and APEL does as well (e.g. the config is read with configparser) would there be objections to porting the report scripts to Python?

I could see moving this script to Python https://github.com/htcondor/htcondor-ce/blob/V5-branch/contrib/apelscripts/condor_batch_blah.sh but it doesn't seem like we'd get much out of changing the service script to Python https://github.com/htcondor/htcondor-ce/blob/V5-branch/contrib/apelscripts/condor_ce_apel.sh.

**Comment by maxfischer2781** [comment]
Thanks for the feedback! That should be enough for a first draft.

> Is this `client.cfg` part of the APEL configuration? Or does this have to live in the HTCondor-CE configuration?

The former, it is one of APEL's configuration files; for reference [here is the default and the relevant section](https://github.com/apel/apel/blob/ef23b80716da51d44a18a82ebf594faaa2e50cf0/conf/client.cfg#L28-L32). As far as I can tell, there is always an APEL client locally on the CE even when the APEL DB itself is distributed/remote.
