### ISSUE TITLE
Inconsistent RequestXYZ for Whole Node Jobs

### ISSUE THREAD

**Issue by maxfischer2781** [htcondor/htcondor-ce#566]
The way that resource requests for WNJ are set is inconsistent so that some are always defined and some may be `UNDEFINED`.

The `RequestCPUs` uses a two-argument `?:` which is not strict and thus eliminates `UNDEFINED` if the `Target` is not available:
https://github.com/htcondor/htcondor-ce/blob/75a6e5e59d6dfab65c50a959c75d838ae2d4d83e/config/01-ce-router-defaults.conf#L188

The `RequestMemory` (and GPU) uses a three-argument `?:` which is strict and thus results in `UNDEFINED` if the `Target` is not available:
https://github.com/htcondor/htcondor-ce/blob/75a6e5e59d6dfab65c50a959c75d838ae2d4d83e/config/01-ce-router-defaults.conf#L232

I'm guessing the intention of the ternaries was to always have the expressions defined, but I'm not sure.

Having this behave inconsistently means scheduling rules, monitoring, ... etc. has neither the correctness of always getting `UNDEFINED` nor the convenience of always having some defined values. Ideally, `RequestCPUs` would use a similar logic than the others, but the other way around may also be worthwhile.

**Comment by JaimeFrey** [comment]
I'm transplanting this issue to JIRA: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1644
